CREATE TABLE USERS
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(20) NOT NULL UNIQUE,
    PASSWORD VARCHAR(10) NOT NULL,
    NAME     VARCHAR(50) NOT NULL,
    EMAIL    VARCHAR(50) NOT NULL
);


CREATE TABLE ITEMS_BID
(
    LISTING_ID BIGINT UNSIGNED NOT NULL,
    USERNAME   VARCHAR(255)    NOT NULL,
    BID        INT             NOT NULL,
    CONSTRAINT FK_USERNAME
        FOREIGN KEY (USERNAME)
            REFERENCES USERS (USERNAME),
    CONSTRAINT FK_LISTING_ID
        FOREIGN KEY (LISTING_ID)
            REFERENCES SELL_FORM_DATA (LISTING_ID)
);


CREATE TABLE SELL_FORM_DATA
(
    LISTING_ID       BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME         VARCHAR(255)    NOT NULL,
    TITLE            VARCHAR(255)    NOT NULL,
    DESCRIPTION      TEXT            NOT NULL,
    FEATURE_A        VARCHAR(255),
    FEATURE_B        VARCHAR(255),
    FEATURE_C        VARCHAR(255),
    FEATURE_D        VARCHAR(255),
    FEATURE_E        VARCHAR(255),
    BIDDING_END_DATE VARCHAR(255)    NOT NULL,
    CATEGORY         VARCHAR(255),
    CONSTRAINT USERNAME_FK
        FOREIGN KEY (USERNAME)
            REFERENCES USERS (USERNAME)
);


DROP TABLE USERS;
DROP TABLE ITEMS_BID;
DROP TABLE SELL_FORM_DATA;